version: '3'
services:
  jupyterlab:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .jupyter:/root/.jupyter
      - ./workspace:/root/workspace
    ports:
      - "127.0.0.1:8888:8888"
    tty: true
    command: jupyter lab --ip=0.0.0.0 --allow-root --notebook-dir=/root/workspace --no-browser --NotebookApp.token=''
